name: termplux
description: TermPlux-App
publish_to: "none"
version: 1.0.0+1
playbox:
  name: termplux
  description: TermPlux-App
  icon: school
  background: blue
environment:
  sdk: ">=2.18.0 <4.0.0"
dependencies:
  flutter: "1.3.0"
  flutter_web_plugins: "1.3.0"
  mpcore: "1.3.0"
  mp_build_tools: "1.3.0"
dependency_overrides:
  flutter: "1.3.0"
  mpcore: "1.3.0"
  flutter_web_plugins: "1.3.0"
