name: termplux
description: TermPlux

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_boost:
    git:
      url: 'https://github.com/alibaba/flutter_boost.git'
      ref: '4.2.2'

  url_strategy: ^0.2.0
  bitsdojo_window: ^0.1.5
  cupertino_icons: ^1.0.2
  dynamic_color: ^1.6.3
  device_preview: ^1.1.0
  webview_flutter: ^4.2.1
  webview_flutter_web: ^0.2.2+1
  xterm: ^3.5.0
  dartssh2: ^2.5.0
  flutter_pty: ^0.3.0
  flutter_rfb: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700